# Generated by Django 2.2.5 on 2019-09-28 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketapp', '0002_auto_20190927_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='InvoiceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_sd', models.PositiveIntegerField(default=10, verbose_name='за 1 сд')),
                ('quantity_sd', models.PositiveIntegerField(default=1, verbose_name='кол-во сд')),
                ('is_processed', models.BooleanField(default=False, verbose_name='проведен')),
                ('comment', models.TextField(blank=True, verbose_name='коментарий')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата заказа')),
                ('date_processed', models.DateTimeField(blank=True, null=True, verbose_name='дата проведения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
