# Generated by Django 2.2.5 on 2019-09-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0003_auto_20190928_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicerequest',
            name='to_pay',
            field=models.PositiveIntegerField(default=10, verbose_name='сумма'),
        ),
    ]
