# Generated by Django 2.2.5 on 2019-09-22 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scriptsuser',
            old_name='scripts_bought',
            new_name='scripts_days',
        ),
    ]
