# Generated by Django 2.2.5 on 2019-09-23 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptsuser',
            name='captain_id',
            field=models.PositiveIntegerField(default=0, verbose_name='имя капитана'),
        ),
        migrations.CreateModel(
            name='UserRights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_edit_scripts', models.BooleanField(default=True, verbose_name='редактирует скрипты')),
                ('can_buy_sd', models.BooleanField(default=True, verbose_name='покупает СД')),
                ('can_edit_users', models.BooleanField(default=True, verbose_name='меняет пользователей')),
                ('can_activate_scripts', models.BooleanField(default=True, verbose_name='запускает скрипты')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
