# Generated by Django 2.2.5 on 2019-09-18 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlToControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='название под-этапа')),
            ],
        ),
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situation', models.CharField(max_length=250, verbose_name='ситуация')),
                ('recomended_action', models.TextField(blank=True, verbose_name='что говорим')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.ControlToControl')),
            ],
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='название скрипта')),
                ('url', models.CharField(max_length=250, verbose_name='ссылка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ControlTop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='название этапа')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Script')),
            ],
        ),
        migrations.AddField(
            model_name='controltocontrol',
            name='control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.ControlTop'),
        ),
    ]
