# Generated by Django 2.2.5 on 2019-09-19 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controltop',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Script'),
        ),
        migrations.AddField(
            model_name='controltocontrol',
            name='control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.ControlTop'),
        ),
    ]
