# Generated by Django 2.2.5 on 2019-09-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_auto_20190920_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='активирован'),
        ),
    ]
