# Generated by Django 2.2.5 on 2019-09-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_auto_20190924_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='controltocontrol',
            name='position',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='позиция'),
        ),
        migrations.AddField(
            model_name='controltop',
            name='position',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='позиция'),
        ),
        migrations.AddField(
            model_name='situation',
            name='position',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='позиция'),
        ),
    ]
