# Generated by Django 2.2.5 on 2019-09-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_script_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
