# Generated by Django 2.2.5 on 2019-09-21 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminapp', '0004_script_last_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script', models.PositiveIntegerField(default=0, verbose_name='ид скрипта')),
                ('is_used', models.BooleanField(default=False, verbose_name='скрипт подключен')),
                ('last_activation', models.DateTimeField(auto_now=True)),
                ('duration_period', models.PositiveIntegerField(default=0, verbose_name='дней активации')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
