# Generated by Django 2.2.5 on 2019-09-22 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_activationslot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivationSlot',
        ),
    ]
